// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package org.example.helloWorld;

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestInsertOrModify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestInsertOrModify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestDelete_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HelloWorld.proto\"f\n\025RequestInsertOrMod" +
      "ify\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\023\n\013usedS" +
      "ervers\030\003 \001(\t\022\034\n\006opType\030\004 \001(\0162\014.OperateTy" +
      "pe\":\n\rRequestDelete\022\013\n\003key\030\001 \001(\t\022\034\n\006opTy" +
      "pe\030\002 \001(\0162\014.OperateType\":\n\rRequestSelect\022" +
      "\013\n\003key\030\001 \001(\t\022\034\n\006opType\030\002 \001(\0162\014.OperateTy" +
      "pe\"\032\n\010Response\022\016\n\006result\030\001 \001(\t*9\n\013Operat" +
      "eType\022\022\n\016InsertOrModify\020\000\022\n\n\006Delete\020\001\022\n\n" +
      "\006Select\020\0022G\n\025OperateInsertOrModify\022.\n\tCa" +
      "lculate\022\026.RequestInsertOrModify\032\t.Respon" +
      "se27\n\rOperateDelete\022&\n\tCalculate\022\016.Reque" +
      "stDelete\032\t.Response27\n\rOperateSelect\022&\n\t" +
      "Calculate\022\016.RequestSelect\032\t.ResponseB\032\n\026" +
      "org.example.helloWorldP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestInsertOrModify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestInsertOrModify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestInsertOrModify_descriptor,
        new java.lang.String[] { "Key", "Value", "UsedServers", "OpType", });
    internal_static_RequestDelete_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestDelete_descriptor,
        new java.lang.String[] { "Key", "OpType", });
    internal_static_RequestSelect_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestSelect_descriptor,
        new java.lang.String[] { "Key", "OpType", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
