// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package org.example.helloWorld;

/**
 * <pre>
 *操作类型
 * </pre>
 *
 * Protobuf enum {@code OperateType}
 */
public enum OperateType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>InsertOrModify = 0;</code>
   */
  InsertOrModify(0),
  /**
   * <code>Delete = 1;</code>
   */
  Delete(1),
  /**
   * <code>Select = 2;</code>
   */
  Select(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>InsertOrModify = 0;</code>
   */
  public static final int InsertOrModify_VALUE = 0;
  /**
   * <code>Delete = 1;</code>
   */
  public static final int Delete_VALUE = 1;
  /**
   * <code>Select = 2;</code>
   */
  public static final int Select_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperateType valueOf(int value) {
    return forNumber(value);
  }

  public static OperateType forNumber(int value) {
    switch (value) {
      case 0: return InsertOrModify;
      case 1: return Delete;
      case 2: return Select;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperateType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperateType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperateType>() {
          public OperateType findValueByNumber(int number) {
            return OperateType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.example.helloWorld.HelloWorld.getDescriptor().getEnumTypes().get(0);
  }

  private static final OperateType[] VALUES = values();

  public static OperateType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperateType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:OperateType)
}

