// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package org.example.helloWorld;

public interface RequestSelectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestSelect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.OperateType opType = 2;</code>
   */
  int getOpTypeValue();
  /**
   * <code>.OperateType opType = 2;</code>
   */
  org.example.helloWorld.OperateType getOpType();
}
