// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package org.example.helloWorld;

public interface RequestInsertOrModifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestInsertOrModify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string usedServers = 3;</code>
   */
  java.lang.String getUsedServers();
  /**
   * <code>string usedServers = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsedServersBytes();

  /**
   * <code>.OperateType opType = 4;</code>
   */
  int getOpTypeValue();
  /**
   * <code>.OperateType opType = 4;</code>
   */
  org.example.helloWorld.OperateType getOpType();
}
